### PR TITLE
Clarify wording in Dos and Don'ts

### PR DESCRIPTION
**Pull request by daneah**
Thanks for providing your incident and postmortem processes for others to learn from!

**What changed?**

* Lead with "Don't" to be more clear about whether a bullet item is something to do or not.
* Make "Dos and Don'ts" pluralized properly

### CODE REVIEW

**Comment by daneah** [comment]
Please feel free to re-open in the future if this is something you have time for or interest in!

**Comment by richadams** [comment]
Oh no, sorry! This totally dropped off my radar!

**Comment by richadams** [comment]
Thanks for the change, and sorry again that I didn't get to this earlier.

**Comment by daneah** [comment]
@richadams no problem, it's always hard to know if things have fallen through the cracks or if folks are just busy, so I don't like to prod too much 😄 thanks for merging!

**Pull request merged**
